Support Mill
ucb-bar/maltese-smt pull request #1
Opened 2021-08-14 05:51 UTC by sequencer

Build from source example:
https://github.com/sequencer/chipsalliance-playground/tree/maltese

2021-08-16 17:50 UTC, ekiwi commented
I would prefer to not have two build files in this repo. Would it be possible to add the mill build file to your `chipsalliance-playground` repository instead?

2021-08-16 18:08 UTC, sequencer commented
Sure.

2021-08-16 18:09 UTC, sequencer commented
Oh I think there is another problem: chiseltest should depend on this, and if we wanna enable build from source it will pain.

2021-08-16 18:15 UTC, ekiwi commented
> Oh I think there is another problem: chiseltest should depend on this, and if we wanna enable build from source it will pain.

OK. Then I would like to ask you for two things:
1. Could you please simplify the mill builds file? Essentially I would like to only have the minimal features that are needed for your to be able to build chiseltest. Publishing to remote for example should not be needed here.
2. Could you add a test for the mill build file to the CI?

2021-08-17 11:32 UTC, sequencer commented
> Could you please simplify the mill builds file? Essentially I would like to only have the minimal features that are needed for your to be able to build chiseltest. Publishing to remote for example should not be needed here.

I make it `PublishScalaModule` is because this:
https://github.com/com-lihaoyi/mill/blob/9d4e55b2feac519497dbc62da70430174e32351b/scalalib/src/PublishModule.scala#L15
restrict a `PublishScalaModule` to be a `PublishModule`, while `Publish` depends on the pom things, which makes hard to clean those up.

> Could you add a test for the mill build file to the CI?

Sure

2021-08-17 15:31 UTC, ekiwi requested changes

2021-08-17 15:31 UTC, ekiwi commented on .github/workflows/test.yml
> +  mill:
Could you please add this job to the dependencies of the `all_tests_passed` job?
Otherwise people will be able to ignore failing mill tests.

2021-08-21 18:27 UTC, sequencer commented
Ask for review again.
Sorry for the delay, I was too busy this week.

2021-08-23 17:23 UTC, ekiwi approved these changes
:shipit:

2021-08-23 17:23 UTC, merged